---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Example assertion
    assert:
      that: true
  - name: vector
      package:
        name: "vector"
        state: "installed"
      check_mode: yes
      register: pkg_status
  - name: vector check
    assert:
      that:
        - not pkg_status.changed
